# Generated by Django 4.2.6 on 2023-10-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute', models.CharField(max_length=10)),
                ('start_timestamp', models.DateTimeField(auto_now_add=True)),
                ('end_timestamp', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.FloatField(default=0.0)),
                ('registed_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boot_switch', models.BooleanField(default=True)),
                ('boot_exclude_holiday', models.BooleanField(default=False)),
                ('boot_exclude_public_holiday', models.BooleanField(default=False)),
                ('register_line_notify_access_token', models.TextField(default='')),
            ],
        ),
    ]
