# Generated by Django 4.2.6 on 2023-10-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webfront', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='settings', max_length=10),
        ),
    ]
